/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.imran.gradle;

public class App {
    public String getGreeting() {
        return "Hello Gradle!";
        
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Product data=new Product("Arman","Web Developer in a top tech Company","20L");
        System.out.println(data);
    }
}
